/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_sin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     TestJNI
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_cos
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     TestJNI
 * Method:    log10
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_log10
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
